### ISSUE TITLE
I have the latest Windows Deps

### ISSUE THREAD

**Issue by scottmudge** [supermerill/SuperSlicer_deps#1]
I have the deps for Windows from the SuperSlicer repo. I can upload them here if you like. Had to make some minor tweaks to the cmake scripts to get them to work.

**Comment by supermerill** [comment]
I have also them from my many computer bur for a reason, I can't compile in the github computer with them.
So for now, i use this repo as a cache for the boost source.

**Comment by scottmudge** [comment]
Gotcha... do you know why CMake has so many problems finding OpenVDB and TBB? I have to manually specify the library and include paths, even though they are right there in the same local folder with everything else. I also have to manually add "libblosc.lib" to the linker inputs in the project configuration, otherwise it won't link against it properly.

**Comment by supermerill** [comment]
no, i never encountered these problems.

**Comment by scottmudge** [comment]
Hmm, probably just my system config. Probably just need to clean up my PATH env variable. 

thanks!
